config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :pacients
  resources :services
  resources :specialties
  resources :dashboard, only: [:index]
  resources :appointments, only: [:index, :create, :update]


  get 'appointment/:id' => 'appointments#appointment_start', as: :appointment_start
  get 'appointment/cancel/:id' => 'appointments#appointment_cancel', as: :appointment_cancel
  get 'appointment/payment/:id' => 'appointments#appointment_payment', as: :appointment_payment
  patch 'appointment/payment/success/:id' => 'appointments#appointment_update', as: :appointment_update
  get 'appointments/finished-of-day' => 'appointments#appointment_finished', as: :appointment_finished
  get 'appointment/detail/:id' => 'appointments#appointment_detail', as: :appointment_detail
  get 'appointments/history/:pacient_id' => 'appointments#appointment_history_all', as: :appointments_history_all
  get 'appointments/of-day/:user_id' => 'appointments#appointments_of_day', as: :appointments_of_day
  get 'appointments/edit-before-pay/:id' => 'appointments#edit_before_pay', as: :edit_before_pay

root 'passthrough#index'
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :appointments, :join_table => :services_appointments

  include PgSearch
  pg_search_scope :search, against: [:name]

 belongs_to :specialty
 belongs_to :appointment, inverse_of: :services, optional: true

 has_many :appointment_services
 has_many :appointments, through: :appointment_services


 validates_presence_of :name, :specialty_id, :price

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:edit, :update, :destroy]
  before_action :accessible_specialties, :only => [:new, :edit, :update, :create]

  respond_to :html, :js, :json

  load_and_authorize_resource

  def index
    if params[:query].present?
      @services = Service.where(deleted_at: nil).search(params[:query])
                                                .paginate(:page => params[:page],
                                                          :per_page => 30)
    else
      @services = Service.where(deleted_at: nil).paginate(:page => params[:page],
                                                          :per_page => 30)
    end
    respond_with(@services)
  end

  def new
    @service = Service.new

    respond_with(@service)
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

   respond_to do |format|
      if @service.save
        flash[:notice] = 'Serviço criado com sucesso!'
        format.html { redirect_to(services_path)}
      else
        format.html { render action: "edit" }
      end
    end
  end

  def update

    respond_to do |format|
      if @service.update(service_params)

        flash[:notice] = 'Serviço editado com sucesso!'
        format.html { redirect_to(services_path) }
      else
        format.html { render action: "edit" }
      end
    end

  end

  def destroy
    @service.deleted_at = Time.now

    respond_to do |format|
      if @service.save!
        flash[:notice] = 'Serviço excluído com sucesso!'
        format.html { redirect_to(services_path) }
      end
    end

  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

  def service_params
    params_list = [:name, :price, :description, :specialty_id]
    params.require(:service).permit(params_list)
  end


end

app/views/services/_form.html.erb
<%= form_for @service, html: { class: 'table-formulary col s12' } do |f| %>
    <a href="<%= services_path %>" class="waves-effect waves-light btn-small right">
      <i class="material-icons">backspace</i>
    </a>
    <div class="input-field col s12">
      <%= f.text_field :name, id: 'name' %>
      <%= f.label :nome_do_serviço %>
    </div>

    <div class="input-field col s6">
      <%= f.text_field :price, id: 'price' %>
      <%= f.label :preço %>
    </div>
    <div class="input-field col s6">
      <%= f.select :specialty_id, @accessible_specialties.collect { |specialty| [ specialty.name, specialty.id ] } %>
      <%= f.label :especialidade %>
    </div>
    <div class="input-field col s12">
      <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
        <i class="material-icons">send</i>
      <% end %>
    </div>
<% end %>

app/views/services/_list.html.erb
<ul class="collection">
   <%= render(@services) %>
</ul>
<div class="row center">
    <%= will_paginate @services %>
</div>

app/views/services/_service.html.erb
 <li class="collection-item">


   <%= link_to service.name, edit_service_path(service) %>
   <%= link_to  service_path(service), method: :delete, class: "secondary-content", data: { confirm: "Você tem certeza?" } do %>
     <i class="material-icons">delete</i>
   <% end %>
 </li>

app/views/services/edit.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Editar Serviço</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @service.errors.any? %>
  <script type="text/javascript">
    <% @service.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>

app/views/services/index.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Serviços</h2>
  </blockquote>
  <div class="row">
      <form class="col s12">
        <div class="input-field col s10">
          <input id="query" type="text" name="query" class="validate">
          <label for="email">Buscar</label>
        </div>
        <div class="search-button col s2">
          <button class="btn waves-effect waves-light" type="submit">
            <i class="material-icons">search</i>
          </button>
        </div>
      </form>
      <%= render 'list'%>
  </div>
  <% if can? :create, Service %>
  <div class="fixed-action-btn">
      <%= link_to(new_service_path, class: "btn-floating btn-large waves-effect waves-light red pulse") do %>
          <i class="material-icons">add</i>
      <% end %>
    </div>
  <% end %>
</div>

<% if !flash[:notice].nil? %>
  <script type="text/javascript">
    M.toast({html: "<%= flash[:notice] %>"});
  </script>
<% end %>

app/views/services/new.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Novo Serviço</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @service.errors.any? %>
  <script type="text/javascript">
    <% @service.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>