config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :pacients
  resources :services
  resources :specialties
  resources :dashboard, only: [:index]
  resources :appointments, only: [:index, :create, :update]


  get 'appointment/:id' => 'appointments#appointment_start', as: :appointment_start
  get 'appointment/cancel/:id' => 'appointments#appointment_cancel', as: :appointment_cancel
  get 'appointment/payment/:id' => 'appointments#appointment_payment', as: :appointment_payment
  patch 'appointment/payment/success/:id' => 'appointments#appointment_update', as: :appointment_update
  get 'appointments/finished-of-day' => 'appointments#appointment_finished', as: :appointment_finished
  get 'appointment/detail/:id' => 'appointments#appointment_detail', as: :appointment_detail
  get 'appointments/history/:pacient_id' => 'appointments#appointment_history_all', as: :appointments_history_all
  get 'appointments/of-day/:user_id' => 'appointments#appointments_of_day', as: :appointments_of_day
  get 'appointments/edit-before-pay/:id' => 'appointments#edit_before_pay', as: :edit_before_pay

root 'passthrough#index'
end

app/models/pacient.rb
class Pacient < ApplicationRecord
    has_and_belongs_to_many :appointments, :join_table => :pacients_appointments
   include PgSearch
   pg_search_scope :search, against: [:name, :email]

   belongs_to :gender
   has_many :appointments

   validates_presence_of :name, :gender_id, :celphone, :birthday,
                         :marital_status

end

app/controllers/pacients_controller.rb
class PacientsController < ApplicationController
  before_action :set_pacient, only: [:edit, :update, :destroy]
  before_action :accessible_genders, :only => [:new, :edit, :update, :create]
  before_action :accessible_specialties, :only => [:index, :new, :edit, :update, :create]

  respond_to :html, :js, :json

  load_and_authorize_resource

  def index
    if params[:query].present?
      @pacients = Pacient.where(deleted_at: nil).search(params[:query])
                                                .order(name: :asc)
                                                .paginate(:page => params[:page],
                                                          :per_page => 30)
    else
      @pacients = Pacient.where(deleted_at: nil).order(name: :asc)
                                                .paginate(:page => params[:page],
                                                          :per_page => 30)
    end
    @appointment = Appointment.new
    respond_with(@pacients)
  end

  def new
    @pacient = Pacient.new

    respond_with(@pacient)
  end

  def edit
    @pacient.birthday = @pacient.birthday.try(:strftime,"%d/%m/%Y")
  end

  def create
    @pacient = Pacient.new(pacient_params)
   respond_to do |format|
      if @pacient.save
        flash[:notice] = 'Paciente criado com sucesso!'
        format.html { redirect_to(pacients_path)}
      else
        format.html { render action: "edit" }
      end
    end
  end

  def update

    respond_to do |format|
      if @pacient.update(pacient_params)

        flash[:notice] = 'Paciente editado com sucesso!'
        format.html { redirect_to(pacients_path) }
      else
        format.html { render action: "edit" }
      end
    end

  end

  def destroy
    @pacient.deleted_at = Time.now

    respond_to do |format|
      if @pacient.save!
        flash[:notice] = 'Paciente excluído com sucesso!'
        format.html { redirect_to(pacients_path) }
      end
    end

  end

  private
    def set_pacient
      @pacient = Pacient.find(params[:id])
    end

  def pacient_params
    params_list = [:email, :name, :cpf, :rg, :cep, :gender_id, :celphone, :birthday, :address,
                   :number, :complement, :profession, :fone, :celphone,
                   :marital_status, :nacionality, :indication,
                   :start_processing, :end_processing]
    params.require(:pacient).permit(params_list)
  end


end

app/views/pacients/_form.html.erb
<%= form_for @pacient, html: { class: 'table-formulary col s12' } do |f| %>
    <a href="<%= pacients_path %>" class="waves-effect waves-light btn-small right">
      <i class="material-icons">backspace</i>
    </a>
    <div class="input-field col s12">
      <%= f.text_field :name, id: 'name' %>
      <%= f.label :nome %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :cpf, id: 'cpf' %>
      <%= f.label :cpf %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :rg, id: 'rg' %>
      <%= f.label :rg %>
    </div>
    <div class="input-field col s8">
      <%= f.text_field :address, id: 'address' %>
      <%= f.label :endereço %>
    </div>
    <div class="input-field col s4">
      <%= f.text_field :cep, id: 'cep' %>
      <%= f.label :cep %>
    </div>
    <div class="input-field col s4">
      <%= f.text_field :number, id: 'number' %>
      <%= f.label :número %>
    </div>
    <div class="input-field col s8">
      <%= f.text_field :complement, id: 'complement' %>
      <%= f.label :complemento %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :birthday, id: 'birthday' %>
      <%= f.label :data_de_nascimento %>
    </div>
    <div class="input-field col s6">
      <%= f.select :marital_status, [['Casado', 'Casado'], ['Solteiro', 'Solteiro'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo'], ['Outro', 'Outro']] %>
      <%= f.label :estado_civil %>
    </div>
    <div class="input-field col s12">
      <%= f.select :gender_id, @accessible_genders.collect { |gender| [ gender.name, gender.id ] } %>
      <%= f.label :sexo %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :fone, id: 'fone' %>
      <%= f.label :telefone %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :celphone, id: 'celphone' %>
      <%= f.label :celular %>
    </div>
    <div class="input-field col s12">
     <%= f.text_field :email, id: 'email' %>
     <%= f.label :email %>
    </div>
    <div class="input-field col s12">
     <%= f.text_field :profession, id: 'profession' %>
     <%= f.label :profissão %>
    </div>
    <div class="input-field col s6">
     <%= f.text_field :nacionality, id: 'nacionality' %>
     <%= f.label :nacionalidade %>
    </div>
    <div class="input-field col s6">
     <%= f.text_field :indication, id: 'indication' %>
     <%= f.label :indicação %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :start_processing, id: 'start_processing' %>
      <%= f.label :inicio_do_tratamento %>
    </div>
    <div class="input-field col s6">
      <%= f.text_field :end_processing, id: 'end_processing' %>
      <%= f.label :fim_do_tratamento %>
    </div>

    <div class="input-field col s12">
      <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
        <i class="material-icons">send</i>
      <% end %>
    </div>
<% end %>

app/views/pacients/_list.html.erb
<ul class="collection">
   <%= render(@pacients) %>
</ul>
<div class="row center">
    <%= will_paginate @pacients %>
</div>

app/views/pacients/_pacient.html.erb
 <li class="collection-item avatar">
   <img src="<%= pacient.gender_id == 1 ? asset_path('patient-male.png') : asset_path('patient-female.png') %>" alt="" class="circle">

   <p>Nome: <%= link_to pacient.name, edit_pacient_path(pacient) %></p>
   <% if can? :create, Appointment %>
      <a class="modal-trigger" href="#mark_consult_<%=pacient.id%>">
        <i class="material-icons tooltipped" data-position="right" data-tooltip="Marcar Consulta">assignment</i>
      </a>
    <% end %>
   <!-- Modal Structure -->
   <div id="mark_consult_<%=pacient.id%>" class="modal">
     <div class="modal-header right">
       <a href="#!" class="modal-close btn waves-effect waves-light">x</a>
     </div>
     <div class="modal-content">
       <h4>Marcar Consulta</h4>
       <%= form_for @appointment, html: { class: 'table-formulary col s12' } do |f| %>
         Paciente: <input type="text" name="" value="<%=pacient.name%>" disabled>
         <input type="hidden" name="appointment[pacient_id]" value="<%=pacient.id%>">
         <div class="input-field col s12">
           <%= f.select :specialty_id, @accessible_specialties.collect { |specialty| [ specialty.name, specialty.id ] } %>
           <%= f.label :especialidade %>
         </div>
         <div class="input-field col s12">
           <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
             <i class="material-icons">send</i>
           <% end %>
         </div>
       <% end %>
     </div>
   </div>
   <% if can? :create, Appointment %>
     <a class="modal-trigger" href="#details_<%=pacient.id%>">
       <i class="material-icons tooltipped" data-position="right" data-tooltip="Histórico de Consultas">history</i>
     </a>
   <% end %>
   <div id="details_<%=pacient.id%>" class="modal bottom-sheet">
     <div class="modal-content">
       <h3 class="header">Histórico de Consultas</h3>
       <ul class="collection">
         <% pacient.appointments.where.not(status: ['buzy', 'wait']).order(created_at: :desc).limit(10).each_with_index do |appointment, index| %>
         <li class="collection-item avatar">
           <img src="/assets/<%= index+1 %>.jpg" alt="" class="circle">
           <span class="title"><%= appointment.specialty.name %></span>
           <p>Médico: <%= appointment.user.name %></p>
           <p>Data: <%= appointment.created_at.strftime("%d-%m-%Y") %></p>
           <p>Status: <%= I18n.t appointment.status %></p>
           <a href="<%= appointment_detail_path(appointment) %>" class="secondary-content">
             <i class="material-icons">grade</i>
           </a>
         </li>
         <% end %>
       </ul>
     </div>
     <div class="modal-footer">
       <a href="#!" class="modal-close waves-effect waves-green btn-flat">FECHAR</a>
     </div>
   </div>
   <% if can? :appointment_history_all, Appointment %>
     <%= link_to appointments_history_all_path(pacient.id) do %>
       <i class="material-icons tooltipped" data-position="right" data-tooltip="Todas as Consultas">reorder</i>
     <% end %>
   <% end %>
   <% if can? :destroy, Pacient %>
     <%= link_to  pacient_path(pacient), method: :delete, class: "secondary-content", data: { confirm: "Você tem certeza?" } do %>
       <i class="material-icons">delete</i>
     <% end %>
   <% end %>

 </li>

app/views/pacients/edit.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Editar Paciente</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @pacient.errors.any? %>
  <script type="text/javascript">
    <% @pacient.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>

app/views/pacients/index.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Pacientes</h2>
  </blockquote>
  <div class="row">
      <form class="col s12">
        <div class="input-field col s10">
          <input id="query" type="text" name="query" class="validate">
          <label for="email">Buscar</label>
        </div>
        <div class="col s2 search-button">
          <button class="btn waves-effect waves-light" type="submit">
            <i class="material-icons">search</i>
          </button>
        </div>
      </form>
      <%= render 'list'%>
  </div>
  <% if can? :create, Pacient %>
    <div class="fixed-action-btn">
      <%= link_to(new_pacient_path, class: "btn-floating btn-large waves-effect waves-light red pulse") do %>
          <i class="material-icons">add</i>
      <% end %>
    </div>
  <% end %>
</div>

<% if !flash[:notice].nil? %>
  <script type="text/javascript">
    M.toast({html: "<%= flash[:notice] %>"});
  </script>
<% end %>

app/views/pacients/new.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Novo Paciente</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @pacient.errors.any? %>
  <script type="text/javascript">
    <% @pacient.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>