config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :pacients
  resources :services
  resources :specialties
  resources :dashboard, only: [:index]
  resources :appointments, only: [:index, :create, :update]


  get 'appointment/:id' => 'appointments#appointment_start', as: :appointment_start
  get 'appointment/cancel/:id' => 'appointments#appointment_cancel', as: :appointment_cancel
  get 'appointment/payment/:id' => 'appointments#appointment_payment', as: :appointment_payment
  patch 'appointment/payment/success/:id' => 'appointments#appointment_update', as: :appointment_update
  get 'appointments/finished-of-day' => 'appointments#appointment_finished', as: :appointment_finished
  get 'appointment/detail/:id' => 'appointments#appointment_detail', as: :appointment_detail
  get 'appointments/history/:pacient_id' => 'appointments#appointment_history_all', as: :appointments_history_all
  get 'appointments/of-day/:user_id' => 'appointments#appointments_of_day', as: :appointments_of_day
  get 'appointments/edit-before-pay/:id' => 'appointments#edit_before_pay', as: :edit_before_pay

root 'passthrough#index'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  # has_and_belongs_to_many :users, :join_table => :appointments_users
  # has_and_belongs_to_many :appointment_services, :join_table => :appointments_services
  # has_and_belongs_to_many :pacients, :join_table => :appointments_pacients

  belongs_to :user, optional: true
  belongs_to :pacient
  belongs_to :specialty, optional: true

  has_many :appointment_services
  has_many :services, through: :appointment_services

  # accepts_nested_attributes_for :appointment_services, reject_if: proc { |attributes| attributes[:id].blank? }

  has_many_attached :images

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:edit, :update, :destroy,
                                         :appointment_start,
                                         :appointment_payment,
                                         :appointment_update,
                                         :appointment_detail,
                                         :appointment_cancel,
                                         :edit_before_pay]
  before_action :accessible_services, :only => [:new, :create,
                                                :appointment_start,
                                                :appointment_payment]

  respond_to :html, :js, :json

  load_and_authorize_resource

  def index
    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    if current_user.role?(:administrator) || current_user.role?(:recepcionista)
      @appointments = Appointment.where(status: 'wait', created_at: today)
                                 .order(created_at: :asc)
                                 .paginate(:page => params[:page],
                                           :per_page => 30)
    else
      @appointments = Appointment.where(status: 'wait', created_at: today,
                                        specialty_id: current_user.specialty_id)
                                 .order(created_at: :asc)
                                 .paginate(:page => params[:page],
                                           :per_page => 30)
    end

    respond_with(@appointments)
  end

  def new
    @appointment = Appointment.new

    respond_with(@appointment)
  end

  def edit
    @services_option = Service.where(specialty_id: current_user.specialty_id,
                                     deleted_at: nil)
                              .map{ |s| [ s.name, s.id ] }
  end

  def create
    @appointment = Appointment.new(appointment_params)

    # @appointment.specialty_id =
    @appointment.status = 'wait'

   respond_to do |format|
      if @appointment.save
        flash[:notice] = 'Consulta Marcada com sucesso!'
        format.html { redirect_to(appointments_path)}
      else
        format.html { render action: "edit" }
      end
    end
  end

  def update

    @appointment.status = "finished"
    @appointment.user_id = current_user.id

    AppointmentService.where(appointment_id: @appointment.id).destroy_all

    AppointmentService.transaction do
      params[:service_ids].each do | service_id |
        @appointment_services = AppointmentService.new
        @appointment_services.appointment_id = @appointment.id
        @appointment_services.service_id = service_id
        @appointment_services.save
      end
    end

    respond_to do |format|
      if @appointment.update(appointment_params)
        p @appointment
        flash[:notice] = 'Consulta Finalizada com sucesso!'
        format.html { redirect_to(appointments_path) }
      else
        format.html { render action: "edit" }
      end
    end

  end

  def appointment_start
    @appointment.status = "buzy"
    @appointment.user_id = current_user.id
    flash[:notice] = 'Paciente em atendimento!' if @appointment.save

     @appointment_services = @appointment.appointment_services.build

    @services_option = Service.where(specialty_id: current_user.specialty_id,
                                     deleted_at: nil)
                              .map{ |s| [ s.name, s.id ] }

    @appointments = Appointment.where(pacient_id: @appointment.pacient_id,
                                      specialty_id: current_user.specialty_id)
                               .where.not(status: ['buzy', 'wait'])
                               .order(created_at: :desc)
                               .limit(30)
  end

  def appointment_cancel

    @appointment.status = "canceled"
    @appointment.user_id = current_user.id

    respond_to do |format|
      if @appointment.save

        flash[:notice] = 'Consulta Cancelada com sucesso!'
        format.html { redirect_to(appointments_path) }
      else
        format.html { render action: "appointment_start" }
      end
    end

  end

  def appointment_finished

    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    if current_user.role?(:administrator) || current_user.role?(:recepcionista)
    @appointments = Appointment.where(status: 'finished', created_at: today)
                               .order(payment_status: :desc)
                               .paginate(page: params[:page],
                                         per_page: 30)
    end
    respond_with(@appointments)
  end

  def appointment_payment
    @total = @appointment.services.sum(:price)
    @total += @appointment.price_optional if !@appointment.price_optional.nil?
    @total -= @appointment.discount if !@appointment.discount.nil?
  end

  def appointment_update

    @appointment.payment_status = "Payed"

    respond_to do |format|
      if @appointment.update(appointment_params)

        flash[:notice] = 'Pagamento Feito com sucesso!'
        format.html { redirect_to(appointment_finished_path) }
      else
        format.html { render action: "edit" }
      end
    end

  end

  def appointment_detail
    @total = @appointment.services.sum(:price)
    @total += @appointment.price_optional if !@appointment.price_optional.nil?
    @total -= @appointment.discount if !@appointment.discount.nil?
    respond_with(@appointment)
  end

  def appointment_history_all

    @appointments = Appointment.where(pacient_id: params[:pacient_id])
                               .order(created_at: :desc)
                               .paginate(:page => params[:page], :per_page => 30)
   @pacient = Pacient.find(params[:pacient_id]);
    respond_with(@appointments)

  end

  def appointments_of_day

    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    if current_user.role?(:medico) || current_user.role?(:dentista)
      @appointments = Appointment.where(status: ['finished', 'buzy'], created_at: today)
                                 .order(created_at: :desc)
                                 .paginate(page: params[:page],
                                           per_page: 30)
    end
    respond_with(@appointments)
  end

  def edit_before_pay
    @services_option = Service.where(specialty_id: current_user.specialty_id,
                                     deleted_at: nil)
                              .map{ |s| [ s.name, s.id ] }

    @appointments = Appointment.where(pacient_id: @appointment.pacient_id,
                                      specialty_id: current_user.specialty_id)
                               .where.not(status: ['buzy', 'wait'])
                               .order(created_at: :desc)
                               .limit(30)

    respond_with(@appointment)
  end


  private
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

  def appointment_params
    params_list = [:pacient_id, :specialty_id, :service_id, :user_id, :price_optional, :discount,
                   :note, :payment_type, images: [], services_params: [:id]]
    params.require(:appointment).permit(params_list)
  end


end

app/views/appointments/_appointment.html.erb
 <li class="collection-item avatar">
   <i class="material-icons circle">subdirectory_arrow_right</i>
   <p><%= appointment.pacient.name %></p>
   <p>Especialidade: <%= appointment.specialty.name %></p>
   <p>Status: <%= appointment.status == 'wait' ? '<span class="green-text">'"#{I18n.t appointment.status}"'</span>'.html_safe : '<span class="red-text">'"#{I18n.t appointment.status}"'</span>'.html_safe %></p>
   <a href="<%= appointment_start_path(appointment) %>" class="secondary-content">
     <i class="material-icons tooltipped" data-position="right" data-tooltip="Atender">send</i>
   </a>
 </li>

app/views/appointments/_form.html.erb
<%= form_for @appointment, html: { class: 'table-formulary col s12' } do |f| %>
    <a href="<%= appointments_path %>" class="waves-effect waves-light btn-small right">
      <i class="material-icons">backspace</i>
    </a>
    <div class="input-field col s12">
      <%= f.select :service_id, @accessible_services.collect { |service| [ service.name, service.id ] }, :disabled => true %>
      <%= f.label :serviço %>
    </div>
    <div class="input-field col s12">
      <%= f.label :paciente %>
      <%= @appointment.pacient.name %>
      <%= f.hidden_field :pacient_id, :value=> @appointment.pacient.id%>
    </div>
    <div class="input-field col s12">
      <%= f.label :médico %>
      <%= current_user.name %>
      <%= f.hidden_field :user_id, :value=> current_user.id %>
    </div>

    <div class="input-field col s12">
      <%= f.label :descrição %>
      <%= f.text_area :note, class: 'materialize-textarea', id: 'description' %>
    </div>

    <div class="input-field col s12">
      <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
        <i class="material-icons">send</i>
      <% end %>
    </div>
<% end %>

app/views/appointments/_list.html.erb
<ul class="collection">
   <%= render(@appointments) %>
</ul>
<div class="row center">
    <%= will_paginate @appointments %>
</div>

app/views/appointments/appointment_detail.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Detalhes do Pagamento</h2>
  </blockquote>
  <div class="row row-table">
        <div class="row description">
          <div class="input-field col s12">
            <label>Serviços:
              <% @appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                  <%= "#{index+1} - " + appointment_services.service.name %>
                  <%= ', ' if index < (@appointment.appointment_services.count - 1)  %>
              <% end %>
            </label>
          </div>
          <div class="input-field col s12">
            <label for="paciente">Paciente: <%= @appointment.pacient.name %></label>
          </div>
          <div class="input-field col s12">
            <label for="medico">Médico: <%= @appointment.user.name %></label>
          </div>
          <div class="input-field col s12">
            <label>Fotos:</label>
          </div>
        </div>
        <div class="row">
          <% @appointment.images.each do |image| %>
            <div class="input-field col s3">
                <%= image_tag image, class: "responsive-img materialboxed" %>
            </div>
          <% end %>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <label>Tipo de Pagamento: <%= @appointment.payment_type %></label>
          </div>
          <% if !@appointment.price_optional.nil? %>
            <div class="input-field col s12">
              <label for="medico">Acréscimo: <%= number_to_currency(@appointment.price_optional) %></label>
            </div>
          <% end
          if !@appointment.discount.nil?
           %>
            <div class="input-field col s12">
              <label for="medico">Desconto: <%= number_to_currency(@appointment.discount) %></label>
            </div>
          <% end %>
          <div class="input-field col s12">
            <label for="medico">Valor Total: <%= number_to_currency(@total) %></label>
          </div>
        </div>


        <div class="input-field col s12">
          <a href="<%= appointment_finished_path %>" class="btn waves-effect waves-light btn-full">
            Voltar
          </a>
        </div>
  </div>
</div>

app/views/appointments/appointment_finished.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Atendimentos Finalizados</h2>
  </blockquote>
  <div class="row">
    <ul class="collection">
      <% @appointments.each do |appointment|

        total = appointment.services.sum(:price)
        total += appointment.price_optional if !appointment.price_optional.nil?
        total -= appointment.discount if !appointment.discount.nil?
        %>

        <li class="collection-item avatar">
          <i class="material-icons circle <%= !appointment.payment_status.nil? ? 'green' : 'red' %>">subdirectory_arrow_right</i>
          <p><%= appointment.pacient.name %></p>
          <p>Serviços:
            <% appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                <%= "#{index+1} - " + appointment_services.service.name %>
                <%= ', ' if index < (appointment.appointment_services.count - 1)  %>
            <% end %>
          </p>
          <p>Médico: <%= appointment.user.name %></p>
          <% if !appointment.price_optional.nil? %>
            <p>Acréscimo: <%= number_to_currency(appointment.price_optional) %></p>
          <% end
             if !appointment.discount.nil? %>
             <p>Desconto: <%= number_to_currency(appointment.discount) %></p>
          <% end %>
          <p>Valor: <%= number_to_currency(total) %></p>
          <% unless !appointment.payment_status.nil? %>
            <a href="<%= appointment_payment_path(appointment) %>" class="secondary-content">
              <i class="material-icons tooltipped" data-position="right" data-tooltip="Pagar">send</i>
            </a>
          <% else %>
          <a href="<%= appointment_detail_path(appointment) %>" class="secondary-content">
            <i class="material-icons tooltipped" data-position="left" data-tooltip="Detalhes"><%= appointment.payment_type == 'Cartão' ? 'credit_card' : 'attach_money' %></i>
          </a>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="row center">
        <%= will_paginate @appointments %>
    </div>

  </div>
</div>

<% if !flash[:notice].nil? %>
  <script type="text/javascript">
    M.toast({html: "<%= flash[:notice] %>"});
  </script>
<% end %>

app/views/appointments/appointment_history_all.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Histórico de Consultas</h2>
    <span class="flow-text"><%= @pacient.name  %></span>
  </blockquote>
  <div class="row">
    <a href="<%= pacients_path %>" class="waves-effect waves-light btn-small right">
      <i class="material-icons tooltipped" data-position="top" data-tooltip="Voltar">backspace</i>
    </a>
  </div>
  <div class="row">
    <ul class="collection">
      <% @appointments.each do |appointment| %>
      <%
         total = appointment.services.sum(:price)
         total += appointment.price_optional if !appointment.price_optional.nil?
         total -= appointment.discount if !appointment.discount.nil?
       %>
        <li class="collection-item avatar">
          <span class="title"><%= appointment.specialty.name %></span>
          <p>Serviço:
            <% appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                <%= "#{index+1} - " + appointment_services.service.name %>
                <%= ', ' if index < (appointment.appointment_services.count - 1)  %>
            <% end %>
          </p>
          <% if !appointment.price_optional.nil? %>
            <p>Acréscimo: <%= appointment.price_optional %></p>
          <% end
           if !appointment.discount.nil?%>
            <p>Desconto: <%= appointment.discount %></p>
          <% end %>
          <p>Valor Total: <%= number_to_currency(total) %></p>
          <p>Médico: <%= appointment.user.name %></p>
          <p>Data: <%= appointment.created_at.strftime("%d-%m-%Y") %></p>
          <p>Status: <%= I18n.t appointment.status %></p>
          <p>Observação: <%= appointment.note %></p>
        </li>
      <% end %>
    </ul>
    <div class="row center">
        <%= will_paginate @appointments %>
    </div>
  </div>
</div>

app/views/appointments/appointment_payment.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Pagamento de  Atendimento</h2>
  </blockquote>
  <div class="row row-table">
    <%= form_for @appointment, url: appointment_update_path, html: { class: 'table-formulary col s12' } do |f| %>
        <a href="<%= appointment_finished_path %>" class="waves-effect waves-light btn-small right">
          <i class="material-icons">cancel</i>
        </a>
        <h5>Dados do atendimento</h5>
        <div class="row description">
          <div class="input-field col s12">
            <label>Serviços:
              <% @appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                  <%= "#{index+1} - " + appointment_services.service.name %>
                  <%= ', ' if index < (@appointment.appointment_services.count - 1)  %>
              <% end %>
            </label>
          </div>
          <div class="input-field col s12">
            <label for="paciente">Paciente: <%= @appointment.pacient.name %></label>
          </div>
          <div class="input-field col s12">
            <label for="medico">Médico: <%= @appointment.user.name %></label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <select name="appointment[payment_type]">
              <option value="Dinheiro">Dinheiro</option>
              <option value="Cartão">Cartão</option>
            </select>
            <label>Tipo de Pagamento</label>
          </div>
          <div class="input-field col s12">
          <% if !@appointment.price_optional.nil? %>
              <label for="medico">Acréscimo: <%= number_to_currency(@appointment.price_optional) %></label>
          </div>
          <% end
             if !@appointment.discount.nil? %>
               <div class="input-field col s12">
                <label for="medico">Desconto: <%= number_to_currency(@appointment.discount) %></label>
              </div>
          <% end %>
          <div class="input-field col s12">
            <label for="medico">Valor Total: <%= number_to_currency(@total) %></label>
          </div>
        </div>


        <div class="input-field col s12">
          <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
            Efetuar Pagamento
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/appointments/appointment_start.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Em Atendimento</h2>
  </blockquote>
  <div class="row row-table">
    <%= form_for @appointment, multiple: true, html: { class: 'table-formulary col s12' } do |f| %>
        <%= link_to  appointment_cancel_path(@appointment), data: { confirm: "Você tem certeza?" }, class: "waves-effect waves-light btn-small right" do %>
          <i class="material-icons">cancel</i>
        <% end %>
        <a class="waves-effect waves-light btn-small modal-trigger" href="#details_<%=@appointment.user_id%>">
          <i class="material-icons tooltipped" data-position="right" data-tooltip="Histórico de Consultas">access_time</i>
        </a>
        <div id="details_<%=@appointment.user_id%>" class="modal bottom-sheet">
          <div class="modal-content">
            <h3 class="header">Histórico de Consultas</h3>
            <ul class="collection">
              <% @appointments.each_with_index do |appointment, index|
                total = appointment.services.sum(:price)
                total += appointment.price_optional if !appointment.price_optional.nil?
                total -= appointment.discount if !appointment.discount.nil?
                %>
              <li class="collection-item avatar">
                <img src="/assets/<%= index+1 %>.jpg" alt="" class="circle">
                <span class="title"><%= appointment.specialty.name %></span>
                <p>Serviço:
                  <% appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                      <%= "#{index+1} - " + appointment_services.service.name %>
                      <%= ', ' if index < (appointment.appointment_services.count - 1)  %>
                  <% end %>
                </p>
                <% if !appointment.price_optional.nil? %>
                  <p>Acréscimo: <%= number_to_currency(appointment.price_optional) %></p>
                <% end
                if !appointment.discount.nil? %>
                  <p>Desconto: <%= number_to_currency(appointment.discount) %></p>
                <% end %>
                <p>Valor Total: <%= number_to_currency(total) %></p>
                <p>Médico: <%= appointment.user.name %></p>
                <p>Data: <%= appointment.created_at.strftime("%d-%m-%Y") %></p>
                <p>Status: <%= I18n.t appointment.status %></p>
                <p>Observação: <%= appointment.note %></p>
              </li>
              <% end %>
            </ul>

          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">FECHAR</a>
          </div>
        </div>


        <h5>Dados do atendimento</h5>
        <div class="row description">
          <div class="input-field col s12">
            <label for="paciente">Paciente: <%= @appointment.pacient.name %></label>
            <%= f.hidden_field :pacient_id, :value=> @appointment.pacient.id%>
          </div>
          <div class="input-field col s12">
            <label for="medico">Médico: <%= current_user.name %></label>
          </div>
        </div>
        <div class="row">
          <div id="appointment_services">
            <div class="nested-fields">
              <div class="input-field col s12">
                <%= select_tag("service_ids[]", options_for_select(@services_option), {:multiple=>true, :required => true}) %>
                <%= label_tag 'Selecionar Serviços:' %>
              </div>
            </div>
          </div>
          <div class="input-field col s6">
            <%= f.text_field :price_optional, id: 'price' %>
            <%= f.label :acrescimo %>
          </div>
          <div class="input-field col s6">
            <%= f.text_field :discount, id: 'price' %>
            <%= f.label :desconto %>
          </div>
          <div class="input-field col s12">
            <%= f.label :descrição %>
            <%= f.text_area :note, class: 'materialize-textarea', id: 'description' %>
          </div>
          <div class="input-field col s12">
            <%= f.file_field :images, direct_upload: true, multiple: true %>
          </div>
        </div>


        <div class="input-field col s12">
          <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
            Finalizar Atendimento
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/appointments/appointments_of_day.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Pacientes Atendidos <%= Time.now.strftime("%d-%m-%Y") %></h2>
  </blockquote>
  <div class="row">
    <ul class="collection">
      <% @appointments.each do |appointment| %>
        <li class="collection-item avatar">
          <i class="material-icons circle <%= !appointment.payment_status.nil? ? 'green' : 'red' %>">subdirectory_arrow_right</i>
          <% if appointment.payment_status.nil? %>
            <%= link_to edit_before_pay_path(appointment) do %>
              <p><%= appointment.pacient.name %></p>
            <% end %>
          <% else %>
            <p><%= appointment.pacient.name %></p>
          <% end %>
          <p>Serviços:
            <% appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                <%= "#{index+1} - " + appointment_services.service.name %>
                <%= ', ' if index < (appointment.appointment_services.count - 1)  %>
            <% end %>
          </p>
          <p>Médico: <%= appointment.user.name %></p>
          <% if !appointment.price_optional.nil? %>
            <p>Acréscimo: <%= number_to_currency(appointment.price_optional) %></p>
          <% end
             if !appointment.discount.nil? %>
             <p>Desconto: <%= number_to_currency(appointment.discount) %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="row center">
        <%= will_paginate @appointments %>
    </div>

  </div>
</div>

<% if !flash[:notice].nil? %>
  <script type="text/javascript">
    M.toast({html: "<%= flash[:notice] %>"});
  </script>
<% end %>

app/views/appointments/edit.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Consulta</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @appointment.errors.any? %>
  <script type="text/javascript">
    <% @appointment.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>

app/views/appointments/edit_before_pay.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Editar Atendimento</h2>
  </blockquote>
  <div class="row row-table">
    <%= form_for @appointment, multiple: true, html: { class: 'table-formulary col s12' } do |f| %>
        <%= link_to  appointment_cancel_path(@appointment), data: { confirm: "Você tem certeza?" }, class: "waves-effect waves-light btn-small right" do %>
          <i class="material-icons">cancel</i>
        <% end %>
        <a class="waves-effect waves-light btn-small modal-trigger" href="#details_<%=@appointment.user_id%>">
          <i class="material-icons tooltipped" data-position="right" data-tooltip="Histórico de Consultas">access_time</i>
        </a>
        <div id="details_<%=@appointment.user_id%>" class="modal bottom-sheet">
          <div class="modal-content">
            <h3 class="header">Histórico de Consultas</h3>
            <ul class="collection">
              <% @appointments.each_with_index do |appointment, index|
                total = appointment.services.sum(:price)
                total += appointment.price_optional if !appointment.price_optional.nil?
                total -= appointment.discount if !appointment.discount.nil?
                %>
              <li class="collection-item avatar">
                <img src="/assets/<%= index+1 %>.jpg" alt="" class="circle">
                <span class="title"><%= appointment.specialty.name %></span>
                <p>Serviço:
                  <% appointment.appointment_services.each_with_index do | appointment_services, index |  %>

                      <%= "#{index+1} - " + appointment_services.service.name %>
                      <%= ', ' if index < (appointment.appointment_services.count - 1)  %>
                  <% end %>
                </p>
                <% if !appointment.price_optional.nil? %>
                  <p>Acréscimo: <%= number_to_currency(appointment.price_optional) %></p>
                <% end
                if !appointment.discount.nil? %>
                  <p>Desconto: <%= number_to_currency(appointment.discount) %></p>
                <% end %>
                <p>Valor Total: <%= number_to_currency(total) %></p>
                <p>Médico: <%= appointment.user.name %></p>
                <p>Data: <%= appointment.created_at.strftime("%d-%m-%Y") %></p>
                <p>Status: <%= I18n.t appointment.status %></p>
                <p>Observação: <%= appointment.note %></p>
              </li>
              <% end %>
            </ul>

          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">FECHAR</a>
          </div>
        </div>


        <h5>Dados do atendimento</h5>
        <div class="row description">
          <div class="input-field col s12">
            <label for="paciente">Paciente: <%= @appointment.pacient.name %></label>
            <%= f.hidden_field :pacient_id, :value=> @appointment.pacient.id%>
          </div>
          <div class="input-field col s12">
            <label for="medico">Médico: <%= current_user.name %></label>
          </div>
        </div>
        <div class="row">
          <div id="appointment_services">
            <div class="nested-fields">
              <div class="input-field col s12">
                <%= select_tag("service_ids[]", options_for_select(@services_option, @appointment.appointment_services.map(&:service_id)), {:multiple=>true, :required => true}) %>
                <%= label_tag 'Selecionar Serviços:' %>
              </div>
            </div>
          </div>
          <div class="input-field col s6">
            <%= f.text_field :price_optional, id: 'price' %>
            <%= f.label :acrescimo %>
          </div>
          <div class="input-field col s6">
            <%= f.text_field :discount, id: 'price' %>
            <%= f.label :desconto %>
          </div>
          <div class="input-field col s12">
            <%= f.label :descrição %>
            <%= f.text_area :note, class: 'materialize-textarea', id: 'description' %>
          </div>
          <div class="input-field col s12">
            <%= f.file_field :images, direct_upload: true, multiple: true %>
          </div>
        </div>


        <div class="input-field col s12">
          <%= f.button nil, :class => 'btn waves-effect waves-light btn-full' do %>
            Finalizar Atendimento
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Lista de Espera</h2>
  </blockquote>
  <div class="row">
    <%= render 'list'%>
  </div>
</div>

<% if !flash[:notice].nil? %>
  <script type="text/javascript">
    M.toast({html: "<%= flash[:notice] %>"});
  </script>
<% end %>

app/views/appointments/new.html.erb
<div class="container">
  <blockquote>
    <h2 class="flow-text">Novo Serviço</h2>
  </blockquote>
  <div class="row row-table">
    <%= render 'form' %>
  </div>
</div>

<% if @appointment.errors.any? %>
  <script type="text/javascript">
    <% @appointment.errors.full_messages.each do |msg| %>
      M.toast({html: "<%= msg %>"});
    <% end %>
  </script>
<% end %>