config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :pacients
  resources :services
  resources :specialties
  resources :dashboard, only: [:index]
  resources :appointments, only: [:index, :create, :update]


  get 'appointment/:id' => 'appointments#appointment_start', as: :appointment_start
  get 'appointment/cancel/:id' => 'appointments#appointment_cancel', as: :appointment_cancel
  get 'appointment/payment/:id' => 'appointments#appointment_payment', as: :appointment_payment
  patch 'appointment/payment/success/:id' => 'appointments#appointment_update', as: :appointment_update
  get 'appointments/finished-of-day' => 'appointments#appointment_finished', as: :appointment_finished
  get 'appointment/detail/:id' => 'appointments#appointment_detail', as: :appointment_detail
  get 'appointments/history/:pacient_id' => 'appointments#appointment_history_all', as: :appointments_history_all
  get 'appointments/of-day/:user_id' => 'appointments#appointments_of_day', as: :appointments_of_day
  get 'appointments/edit-before-pay/:id' => 'appointments#edit_before_pay', as: :edit_before_pay

root 'passthrough#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClinicSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="ClinicSystem">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script type="text/javascript">
      function tooltipMessage(message){
        M.toast({html: message});
      }
    </script>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper orange darken-4">
        <a href="" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="left hide-on-med-and-down">
          <% if can? :index, Pacient %>
            <li><a href="<%= pacients_path %>" class="tooltipped" data-position="bottom" data-tooltip="Pacientes"><i class="material-icons" >group</i></a></li>
          <% end %>
          <% if can? :index, Appointment %>
            <li><a href="<%= appointments_path %>" class="tooltipped" data-position="bottom" data-tooltip="Consultas do dia"><i class="material-icons">event_available</i></a></li>
          <% end %>
          <% if can? :appointment_finished, Appointment %>
            <li><a href="<%= appointment_finished_path %>" class="tooltipped" data-position="bottom" data-tooltip="Pagamentos do Dia"><i class="material-icons">payment</i></a></li>
          <% end %>
          <% if can? :index, Service %>
            <li><a href="<%= services_path %>" class="tooltipped" data-position="bottom" data-tooltip="Serviços"><i class="material-icons">business_center</i></a></li>
          <% end %>
          <% if can? :index, Specialty %>
            <li><a href="<%= specialties_path %>" class="tooltipped" data-position="bottom" data-tooltip="Especialidades"><i class="material-icons">group_work</i></a></li>
          <% end %>
          <% if can? :create, User %>
            <li><a href="<%= users_path %>" class="tooltipped" data-position="bottom" data-tooltip="Usuários"><i class="material-icons">group</i></a></li>
          <% end %>
          <% if can? :appointments_of_day, Appointment %>
            <li><a href="<%= appointments_of_day_path(current_user.id) %>" class="tooltipped" data-position="bottom" data-tooltip="Atendimentos do Dia"><i class="material-icons">check</i></a></li>
          <% end %>
        </ul>
        <ul class="right hide-on-med-and-down">

          <li>
            <%= link_to destroy_user_session_path, :method => :delete, class: "waves-effect tooltipped", data: {"position" => "bottom", "tooltip" => "Sair"} do %>
              <i class="material-icons">power_settings_new</i>
            <%end %>
          </li>
        </ul>
      </div>
    </nav>

    <ul id="mobile-demo" class="sidenav show-on-medium-and-down">
      <li><div class="user-view">
        <div class="background">
          <img src="<%= asset_path('dentist-background-profile.png') %>">
        </div>
        <img class="circle" src="<%= asset_path(current_user.avatar) %>">
        <span class="white-text name"><%= current_user.name %></span>
        <span class="white-text email"><%= current_user.email %></span>
      </div></li>
      <% if can? :index, Pacient %>
        <li><a href="<%= pacients_path %>"><i class="material-icons">group</i>Pacientes</a></li>
      <% end %>
      <% if can? :index, Appointment %>
        <li><a href="<%= appointments_path %>"><i class="material-icons">event_available</i>Consultas do dia</a></li>
      <% end %>
      <% if can? :appointment_finished, Appointment %>
        <li><a href="<%= appointment_finished_path %>"><i class="material-icons">payment</i>Pagamentos do Dia</a></li>
      <% end %>
      <% if can? :index, Service %>
        <li><a href="<%= services_path %>"><i class="material-icons">business_center</i>Serviços</a></li>
      <% end %>
      <% if can? :index, Specialty %>
        <li><a href="<%= specialties_path %>"><i class="material-icons">group_work</i>Especialidades</a></li>
      <% end %>
      <% if can? :appointments_of_day, Appointment %>
        <li><a href="<%= appointments_of_day_path(current_user.id) %>"><i class="material-icons">check</i>Atendimentos do Dia</a></li>
      <% end %>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Outras opções</a></li>
      <% if can? :manager, User %>
        <li><a href="<%= users_path %>"><i class="material-icons">group</i>Usuários</a></li>
      <% end %>
      <li>
        <%= link_to destroy_user_session_path, :method => :delete, class: "waves-effect tooltipped" do %>
          <i class="material-icons">power_settings_new</i>Sair
        <%end %>
      </li>
    </ul>
    <div class="row">
      <%= yield %>
    </div>
    </div>
    <script>
    $(document).ready(function() {
       $('.tooltipped').tooltip();
       $('.sidenav').sidenav();
       $('select').formSelect();
       $('.fixed-action-btn').floatingActionButton();
       $('.modal').modal();
       $('.materialboxed').materialbox();
       $('select').formSelect();
     });
    </script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClinicSystem | Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>

    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="description" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Clinic System">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript">
      function tooltipMessage(message){
        M.toast({html: message});
      }
    </script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>